### PR TITLE
Set reasonable default

### PR DESCRIPTION
**Pull request by albertmink**
I struggled to use our tool, because of the field label. Maybe a reasonable default sorts out this kind of confusion.

### CODE REVIEW

**Comment by albertmink** [comment]
I just wonder why we ask the user to provide an object type (e.g. `CLAS`), when it is the interface (e.g. `IF_AFF_CLAS_V1`) that determines the JSON schema and simple transformation.

**Comment by huber-nicolas** [comment]
In which system did you do the changes? I can not find your changes in z_generate_json_schema in system UIA

**Comment by huber-nicolas** [comment]
> I just wonder why we ask the user to provide an object type (e.g. `CLAS`), when it is the interface (e.g. `IF_AFF_CLAS_V1`) that determines the JSON schema and simple transformation.

I introduced the object_type textfield so that for testing purposes also other interfaces than if_aff_<objecttype> can be used

**Comment by albertmink** [comment]
As the PROG shall work with the interface from the AFF repository, there is no need to allow for all interface names. I prefer to reduce the ambiguity for UIs. If I have to provide the information twice, it feels wrong and I begin to doubt 😟
For testing, you can still use the PROG and vary the interface name by `zif_aff_ABC_clas` or any other combination, right?

**Review by huber-nicolas — APPROVED** [review]

**Pull request merged**
