### PR TITLE
Add interface for generator

### PR DESCRIPTION
**Pull request by wurzka**
Added interface for zcl_aff_generator.

In this way, it is easier to mock generator during unit tests.

### CODE REVIEW

**Review by schneidermic0 — APPROVED** [review]
Looks good to me

**Comment by larshp** [comment]
note the error 

`Method "generate_type" not found, methodCallChain, cl_run.clas.abap:34`

is in `cl_run`, https://github.com/SAP/abap-file-formats-tools/blob/main/test/cl_run.clas.abap

**Comment by wurzka** [comment]
Ah thanks, I only checked the classes in our system, but not the classes in the test folder

**Review by schneidermic0 — APPROVED** [review]
Looks good to me, now.

**Pull request merged**
