### PR TITLE
Remove database select

### PR DESCRIPTION
**Pull request by wurzka**
Instead of selection from the database teh class cl_oo_classname_service is called

### CODE REVIEW

**Comment by wurzka** [comment]
Closes #50

**Comment by wurzka** [comment]
Yes, that is correct. And we can imagine adding this interface in the future. But in our opinion, this effort is currently not worth it.

**Comment by larshp** [comment]
interfaces work out of the box in the transpiler/open-abap, `cl_oo_classname_service=>get_all_method_includes` does not plus

**Comment by larshp** [comment]
plus I think compile time errors is preferable over runtime

**Comment by wurzka** [comment]
Actually, object type specific callback classes are only used once and should only be used if there is no other possible solution. We want to wait with adding the interface until there is more need for it.

What do you mean with `cl_oo_classname_service=>get_all_method_includes` does not work out of the box? Should we not use this method then?

**Comment by larshp** [comment]
okay, next suggestion: delete `METHOD is_callback_class_valid.` and just let the code dump if the class is not valid(does not implement the correct interface), the methods in the class are called dynamically anyhow

**Comment by albertmink** [comment]
I just created a a new issue that refers to the above comment, as I believe this has a bigger impact of the behavior. The mentioned method is mostly used for convenience and to have a central place where the error/warning/info message is collect into the cl_aff_log - afaik.

**Review by albertmink — APPROVED** [review]
Looks good to me.
See comment above

**Pull request merged**
