### PR TITLE
Update abap-syntax version to 757, REGEX->PCRE

### PR DESCRIPTION
**Pull request by albertmink**
see https://github.com/abaplint/abaplint/issues/3096

### CODE REVIEW

**Comment by larshp** [comment]
gonna run into runtime errors too,
image

**Comment by albertmink** [comment]
Alright @larshp, I didn't expect this one, but hey it is a 'TODO' so it is not an error. Let's keep this PR open, as we don't need to rush

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/3102

**Comment by larshp** [comment]
next = https://github.com/abaplint/transpiler/pull/1322

**Review by larshp — APPROVED** [review]
lgtm

**Pull request merged**
