### PR TITLE
Add annotation for setting own enum values

### PR DESCRIPTION
**Pull request by wurzka**
Until now, the possible enum values are taken from the names of the components of a constant transformed to camel case.
Now, we want to allow setting own enum values by using a new annoation.

In a first step, I extended the ABAP Doc Parser so that the new annotation `$enumValue 'value' ` can be used.

### CODE REVIEW

**Comment by wurzka** [comment]
@huber-nicolas @albertmink  What do you think about the new annotation `$enumValue` ? Any suggestions for improvement?

**Comment by albertmink** [comment]
Is this a different way of providing the ENUM values than [here ](https://github.com/SAP/abap-file-formats/blob/main/file-formats/zif_aff_types_v1.intf.abap#L11)?
I don't know exactly how to use this feature. The unit test tells me something, but I cannot translate the information into JSON Schema ;(

**Comment by wurzka** [comment]
It is an extension. You still provide the constant like this.
But the components of the constant can now be annotated with `$enumValue 'newEnumValue'`
Then, not the name of the component transformed to camel case is used as enum value but `newEnumValue`.
See this [issue](https://github.com/SAP/abap-file-formats/issues/312) as reference

**Comment by albertmink** [comment]
Now I remember. The name of the annotation `enumValue` is good. The JSON Schema does have `enum`, `enumTitles` and `enumDescriptions`. So adding an `enumValue` as ABAP annotation is fine.

**Review by albertmink — APPROVED** [review]

**Pull request merged**
