### PR TITLE
downport & transpiling

### PR DESCRIPTION
**Pull request by larshp**
* set syntax check to full/strict scope
* add custom dependencies
* setup downport setup
* setup transpiling step

see scripts in https://github.com/SAP/abap-file-formats-tools/blob/hvam/deps2004/package.json#L7-L10

it does not work yet, so CI/actions is not setup yet

### CODE REVIEW

**Comment by larshp** [comment]
requires https://github.com/SAP/abap-file-formats-tools/pull/64 to be merged first

**Comment by larshp** [comment]
requires https://github.com/SAP/abap-file-formats-tools/issues/67

**Review by albertmink — APPROVED** [review]
Is this the starting point of some magic outside the ABAP system?

**Comment by larshp** [comment]
yes

**Pull request merged**
