### PR TITLE
Standalone ABAP doc reader

### PR DESCRIPTION
**Pull request by schneidermic0**
Ref #72 

Feel free to continue to work on this PR

### CODE REVIEW

**Comment by albertmink** [comment]
- [ ] Replace RSWSOURCET data type, compare a1486a0

**Comment by larshp** [comment]
last error is a false positive by abaplint, will try fixing it in abaplint first

**Review by larshp — APPROVED** [review]

**Comment by larshp** [comment]
also started some implementation of SCAN = https://github.com/open-abap/open-abap/pull/315

**Comment by schneidermic0** [comment]
@larshp Thanks for taking over. I had no time during the last two weeks :(

**Pull request merged**
