### PR TITLE
remove some pragmas and update linter config to latest

### PR DESCRIPTION
**Pull request by larshp**
##NEEDED is not needed if there are no definitions

##NO_TEXT is not needed if there are no texts

plus pragmas changed to UPPER CASE

### CODE REVIEW

**Comment by albertmink** [comment]
The abap files in the pull request don't have an empty line at the end-of-file. Does this align with the file format  in abapGit?

**Comment by albertmink** [comment]
I just pulled the branch to an ABAP system an the affected classes/files have an empty?! diff, see
image
Selective pull does not resolve this diff.

Does abapgit specify the EOF style? If so, we could include this into the editorconfig.

**Comment by larshp** [comment]
well, I think for now its not important

when this repository moves to use the abap-file-format, it should follow that spec, where we have a well defined expectation

**Comment by albertmink** [comment]
Let's move forward and merge, since we can fix the EOF later.
/*
Personally, I cannot understand how there can be text editors that don't insert standard (posix) of EOF marker. It is an issue in abapGit (see screenshot above) as for any git client 
image
If there are no changes, there should be no diff. This diff, however, exists and does not show changes -> confuses the user.
*/

**Review by albertmink — APPROVED** [review]
Looks good to me.

**Pull request merged**
