### PR TITLE
Check z_generate_repo by abaplint

### PR DESCRIPTION
**Pull request by albertmink**
This PR makes report `z_generate_repo` fit to pass abapLint checks 💪

The value help will no longer be alphabetically sorted, see 
Screenshot 2023-10-09 at 13 48 30

After #281 as there is a new keyword `STEP`

### CODE REVIEW

**Comment by albertmink** [comment]
For now ignoring local classes `ltc_generator_double` and `ltc_generator` as they are non-productive coding.

**Comment by larshp** [comment]
https://rules.abaplint.org/indentation/

try setting `"selectionScreenBlockIndentation": true,`

**Comment by larshp** [comment]
```
"indentation": {
  "selectionScreenBlockIndentation": true
},
```

**Comment by larshp** [comment]
db_operation_in_loop: for now, just exclude the program in the rule setting

**Review by wurzka — APPROVED** [review]
Looks good to me 👍

**Review by huber-nicolas — APPROVED** [review]

**Pull request merged**
